-- AuthSession
ALTER TABLE "AuthSession" ADD COLUMN IF NOT EXISTS "revokedAt" TIMESTAMP(3);

-- User
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "engineerId" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "clientId" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "passwordHash" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "mfaEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "currentImpersonationId" TEXT;

ALTER TABLE "User" ALTER COLUMN "companyId" DROP NOT NULL;
