-- AlterTable
ALTER TABLE "Agreement" ADD COLUMN IF NOT EXISTS "clientPdfKey" TEXT;
ALTER TABLE "Agreement" ADD COLUMN IF NOT EXISTS "auditPdfKey" TEXT;
ALTER TABLE "Agreement" ADD COLUMN IF NOT EXISTS "clientPdfAt" TIMESTAMP(3);
ALTER TABLE "Agreement" ADD COLUMN IF NOT EXISTS "auditPdfAt" TIMESTAMP(3);
